//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fruit
    {
        public int FruitType { get; set; }
        public string FruitName { get; set; }
        public Nullable<int> Calories { get; set; }
    }
}
