//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightTracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeightTrackerDatabaseEntities : DbContext
    {
        public WeightTrackerDatabaseEntities()
            : base("name=WeightTrackerDatabaseEntities")
        {
        }
        public DbSet[] Category = new DbSet[5];
        public void Meal()
        {
            Category = new DbSet[] { FoodIntakes, Fruits };
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dairy_Non_liquid_> Dairy_Non_liquid_ { get; set; }
        public virtual DbSet<FoodIntake> FoodIntakes { get; set; }
        public virtual DbSet<Fruit> Fruits { get; set; }
        public virtual DbSet<Meat> Meats { get; set; }
        public virtual DbSet<Seafood> Seafoods { get; set; }
        public virtual DbSet<Sweet> Sweets { get; set; }
        public virtual DbSet<Vegetable> Vegetables { get; set; }
        public virtual DbSet<Wheat> Wheats { get; set; }
    }
}
